api = "0.2"

[buildpack]
  id = "paketo-buildpacks/dotnet-core-runtime"
  name = "Paketo .NET Core Runtime Buildpack"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-runtime"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    deprecation_date = "2021-08-21T00:00:00Z"
    id = "dotnet-runtime"
    sha256 = "7f73229433859bbe1e383969e8db07ce8fef1ec1bea53507484fa606600fc66b"
    source = "https://download.visualstudio.microsoft.com/download/pr/f7eb39c4-484d-4e01-bd41-b4fe6794cd82/ff5c2799f30ea6dd19964c5c90780dba/dotnet-runtime-2.1.27-linux-x64.tar.gz"
    source_sha256 = "9d4e8c6c65939dd755e51e11f855f09c187d756b8bb6476ffb0419e539e57f5a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_2.1.27_linux_x64_any-stack_7f732294.tar.xz"
    version = "2.1.27"

  [[metadata.dependencies]]
    deprecation_date = "2021-08-21T00:00:00Z"
    id = "dotnet-runtime"
    sha256 = "9c20974f100ad5f8938b3658636d48d84b07391ee66a76c3ae4a47d0b6b32d79"
    source = "https://download.visualstudio.microsoft.com/download/pr/95e68908-4a59-4adb-a44f-116914572423/7f8ee037851be82c8a583f47ee2969a7/dotnet-runtime-2.1.28-linux-x64.tar.gz"
    source_sha256 = "b952518ec11e7992a4c22989154c16356def3ffdb3bf9b2ae8681c6968e41777"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_2.1.28_linux_x64_any-stack_9c20974f.tar.xz"
    version = "2.1.28"

  [[metadata.dependencies]]
    deprecation_date = "2022-12-04T00:00:00Z"
    id = "dotnet-runtime"
    sha256 = "b256d9fa93a3a7b2d69663f7f3c19040b582d1bd0338d1934b3f9330405fe44d"
    source = "https://download.visualstudio.microsoft.com/download/pr/45774232-d104-4ef6-a22d-9412288c0062/4b6f2462a7ccc8899950a8641631d65d/dotnet-runtime-3.1.16-linux-x64.tar.gz"
    source_sha256 = "6b638e51d5688c7c58859f9220e28576b381cad91b1aa12e6049fdb6f5ef4eea"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_3.1.16_linux_x64_any-stack_b256d9fa.tar.xz"
    version = "3.1.16"

  [[metadata.dependencies]]
    deprecation_date = "2022-12-04T00:00:00Z"
    id = "dotnet-runtime"
    sha256 = "02a6437a9f97d12917c03a13f8040e644343b1704fd68b74af5be60e24c02405"
    source = "https://download.visualstudio.microsoft.com/download/pr/7a4bfa73-e500-45aa-8e10-04dc4910d8ae/f8b74c973752d3ea095fe06aa625f7f7/dotnet-runtime-3.1.17-linux-x64.tar.gz"
    source_sha256 = "678154c84e1034a4b094a210a8e9dec08fb0dbc5cde3304a85d549d9e6762a75"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_3.1.17_linux_x64_any-stack_02a6437a.tar.xz"
    version = "3.1.17"

  [[metadata.dependencies]]
    id = "dotnet-runtime"
    sha256 = "bcfd1d24c2940b407a1c7b09936da59551615be191ae28132a6b898fe184c4ee"
    source = "https://download.visualstudio.microsoft.com/download/pr/f229fc63-747e-46c8-89ac-88563c2e0b7d/8e59115deda958a26e1546f603cbad9a/dotnet-runtime-5.0.7-linux-x64.tar.gz"
    source_sha256 = "ed864299f0e736f9d284b655e62d8a29aee97c14741ef8baf13d5ff493f83a47"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_5.0.7_linux_x64_any-stack_bcfd1d24.tar.xz"
    version = "5.0.7"

  [[metadata.dependencies]]
    id = "dotnet-runtime"
    sha256 = "d746012f2ec580a151bef0fe1ea4bcebf5098b17487535089a00c3a331ec3217"
    source = "https://download.visualstudio.microsoft.com/download/pr/50687c84-e120-4410-bd4a-b1e0869d03f4/6038576259f95ef61d4d103ee3967130/dotnet-runtime-5.0.8-linux-x64.tar.gz"
    source_sha256 = "2a729240c6518c7c995769b1be7757e2e0388a58dca65236561a300f60ef096a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_5.0.8_linux_x64_any-stack_d746012f.tar.xz"
    version = "5.0.8"

  [[metadata.dependency_deprecation_dates]]
    date = "2021-08-21T00:00:00Z"
    link = "https://dotnet.microsoft.com/platform/support/policy/dotnet-core"
    name = "dotnet-runtime"
    version_line = "2.1.x"

  [[metadata.dependency_deprecation_dates]]
    date = "2022-12-04T00:00:00Z"
    link = "https://dotnet.microsoft.com/platform/support/policy/dotnet-core"
    name = "dotnet-runtime"
    version_line = "3.1.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
