api = "0.8"

[buildpack]
  description = "A buildpack for installing the appropriate .NET Core runtime version"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-runtime"
  id = "paketo-buildpacks/dotnet-core-runtime"
  keywords = ["dotnet", "runtime"]
  name = "Paketo Buildpack for .NET Core Runtime"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/dotnet-core-runtime/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    dotnet-runtime = "6.0.*"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net_core:3.1.28:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-13T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core Runtime"
    purl = "pkg:generic/dotnet-runtime@3.1.28?checksum=dbb5552b8082b22d0a348291d030b324cf4e4c7d409dccb6fb3c859b9f16a114&download_url=https://download.visualstudio.microsoft.com/download/pr/9a0b8ff8-d3da-4e77-9b5b-2fb3202afbbe/94dbcaacd4ebf59106a141c8e9e84167/dotnet-runtime-3.1.28-linux-x64.tar.gz"
    sha256 = "f5f25f3151e0c89d86b9bf9258f7db95a54e9476335e1585a7a58f2956e17cef"
    source = "https://download.visualstudio.microsoft.com/download/pr/9a0b8ff8-d3da-4e77-9b5b-2fb3202afbbe/94dbcaacd4ebf59106a141c8e9e84167/dotnet-runtime-3.1.28-linux-x64.tar.gz"
    source_sha256 = "dbb5552b8082b22d0a348291d030b324cf4e4c7d409dccb6fb3c859b9f16a114"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_3.1.28_linux_x64_bionic_f5f25f31.tar.xz"
    version = "3.1.28"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net_core:3.1.29:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-13T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core Runtime"
    purl = "pkg:generic/dotnet-runtime@3.1.29?checksum=c9d1a4e88cc5801c93aaa2448521d5eed5045ee46a0ce1f4a33b6efaed796c11&download_url=https://download.visualstudio.microsoft.com/download/pr/8a8cff44-0a23-413a-8643-2a0fa3b4da3c/c937fe6ed4d60efb1ef2929d983398cd/dotnet-runtime-3.1.29-linux-x64.tar.gz"
    sha256 = "319dbf1a8699724f7e1a6856a77f2cf41d784953913a78aa6349690f9cab3fc4"
    source = "https://download.visualstudio.microsoft.com/download/pr/8a8cff44-0a23-413a-8643-2a0fa3b4da3c/c937fe6ed4d60efb1ef2929d983398cd/dotnet-runtime-3.1.29-linux-x64.tar.gz"
    source_sha256 = "c9d1a4e88cc5801c93aaa2448521d5eed5045ee46a0ce1f4a33b6efaed796c11"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_3.1.29_linux_x64_bionic_319dbf1a.tar.xz"
    version = "3.1.29"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net:6.0.8:*:*:*:*:*:*:*"
    deprecation_date = "2024-11-12T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core Runtime"
    purl = "pkg:generic/dotnet-runtime@6.0.8?checksum=be20edcb435e3505f661b01a0d363378f9e067fdd05e21b177817f072d43b2dd&download_url=https://download.visualstudio.microsoft.com/download/pr/5596ef6f-a174-4fba-aef1-99173e3f3c67/77edd755d605688885ca7114bc4f9ae9/dotnet-runtime-6.0.8-linux-x64.tar.gz"
    sha256 = "1d3ebec9c63dc5f4b32fa6f36f36c84d48f38cd4790dab0874b17d1f848bf267"
    source = "https://download.visualstudio.microsoft.com/download/pr/5596ef6f-a174-4fba-aef1-99173e3f3c67/77edd755d605688885ca7114bc4f9ae9/dotnet-runtime-6.0.8-linux-x64.tar.gz"
    source_sha256 = "be20edcb435e3505f661b01a0d363378f9e067fdd05e21b177817f072d43b2dd"
    stacks = ["io.buildpacks.stacks.bionic", "io.buildpacks.stacks.jammy"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_6.0.8_linux_x64_bionic_1d3ebec9.tar.xz"
    version = "6.0.8"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net:6.0.9:*:*:*:*:*:*:*"
    deprecation_date = "2024-11-12T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core Runtime"
    purl = "pkg:generic/dotnet-runtime@6.0.9?checksum=3ffe807c2f0efc81410d31d96f7c1278cd1a2357d71da790e59b04e48d3231c5&download_url=https://download.visualstudio.microsoft.com/download/pr/05f1a3dd-75f2-49f4-a976-25ce08f77cbb/b6e8e327a84b91513c2744bfccf90140/dotnet-runtime-6.0.9-linux-x64.tar.gz"
    sha256 = "a691f754903789bd990106ae8e8da4c12116b2c103cef0f020f60c19dd6cb35b"
    source = "https://download.visualstudio.microsoft.com/download/pr/05f1a3dd-75f2-49f4-a976-25ce08f77cbb/b6e8e327a84b91513c2744bfccf90140/dotnet-runtime-6.0.9-linux-x64.tar.gz"
    source_sha256 = "3ffe807c2f0efc81410d31d96f7c1278cd1a2357d71da790e59b04e48d3231c5"
    stacks = ["io.buildpacks.stacks.bionic", "io.buildpacks.stacks.jammy"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_6.0.9_linux_x64_bionic_a691f754.tar.xz"
    version = "6.0.9"

  [[metadata.dependency-constraints]]
    constraint = "3.1.*"
    id = "dotnet-runtime"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "6.0.*"
    id = "dotnet-runtime"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.buildpacks.stacks.jammy"
