api = "0.6"

[buildpack]
  description = "A buildpack for installing the approriate .NET Core runtime version"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-runtime"
  id = "paketo-buildpacks/dotnet-core-runtime"
  keywords = ["dotnet", "runtime"]
  name = "Paketo .NET Core Runtime Buildpack"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/dotnet-core-runtime/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    dotnet-runtime = "5.0.*"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net_core:3.1.21:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-03T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-runtime@3.1.21?checksum=0ea93fc00d58f90b0455277f6f57dfc693c0cf6c85c8a371e0d6e80cafce6352&download_url=https://download.visualstudio.microsoft.com/download/pr/286e526e-282b-47e5-afeb-4f99ee481972/495908d6a6019e47249bd05f8346aeb5/dotnet-runtime-3.1.21-linux-x64.tar.gz"
    sha256 = "f651c2a2b4f0c7f372c9ec8027eca141373529c5d7ce549b8a28e756ceeb4210"
    source = "https://download.visualstudio.microsoft.com/download/pr/286e526e-282b-47e5-afeb-4f99ee481972/495908d6a6019e47249bd05f8346aeb5/dotnet-runtime-3.1.21-linux-x64.tar.gz"
    source_sha256 = "0ea93fc00d58f90b0455277f6f57dfc693c0cf6c85c8a371e0d6e80cafce6352"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_3.1.21_linux_x64_bionic_f651c2a2.tar.xz"
    version = "3.1.21"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net_core:3.1.22:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-03T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-runtime@3.1.22?checksum=8a5b1a9a8ca0b927450c14671e879f5e1d99906e4b67e2933047c888fda879e1&download_url=https://download.visualstudio.microsoft.com/download/pr/8a11a2ba-d599-486f-ba61-9e420bc4a2bb/db9d61f28e0a688adc83687b611702ff/dotnet-runtime-3.1.22-linux-x64.tar.gz"
    sha256 = "a0e5fc49247e55b3c290647e16a12c5ca312c34c4796822ac37be21b583dff59"
    source = "https://download.visualstudio.microsoft.com/download/pr/8a11a2ba-d599-486f-ba61-9e420bc4a2bb/db9d61f28e0a688adc83687b611702ff/dotnet-runtime-3.1.22-linux-x64.tar.gz"
    source_sha256 = "8a5b1a9a8ca0b927450c14671e879f5e1d99906e4b67e2933047c888fda879e1"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_3.1.22_linux_x64_bionic_a0e5fc49.tar.xz"
    version = "3.1.22"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net:5.0.13:*:*:*:*:*:*:*"
    deprecation_date = "2022-05-08T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-runtime@5.0.13?checksum=14ee48371753c4235d3c6df865c1106ff689f262e175ddbcfee82aa6e23f8e11&download_url=https://download.visualstudio.microsoft.com/download/pr/60ab6867-f33d-4708-8eb0-83018e4c22bd/04fb765d876f26c50cdc818323e6aaa6/dotnet-runtime-5.0.13-linux-x64.tar.gz"
    sha256 = "844b4d7a8490b9b187854dfadcf283b3cbab873ae8d012af41583f6e46e997e3"
    source = "https://download.visualstudio.microsoft.com/download/pr/60ab6867-f33d-4708-8eb0-83018e4c22bd/04fb765d876f26c50cdc818323e6aaa6/dotnet-runtime-5.0.13-linux-x64.tar.gz"
    source_sha256 = "14ee48371753c4235d3c6df865c1106ff689f262e175ddbcfee82aa6e23f8e11"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_5.0.13_linux_x64_bionic_844b4d7a.tar.xz"
    version = "5.0.13"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net:5.0.14:*:*:*:*:*:*:*"
    deprecation_date = "2022-05-08T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-runtime@5.0.14?checksum=4e8b468612c6903167c729f32f41d2b0e703fec767e165ed9d5038da6e92d579&download_url=https://download.visualstudio.microsoft.com/download/pr/c7e0c48d-e0ce-4ef9-b30b-41a66a078b0a/26cba85b178af0458f09830a93ab956b/dotnet-runtime-5.0.14-linux-x64.tar.gz"
    sha256 = "b75dd3b7b8f8059388749c85cf9b2668cd01ce1f8e91c902a883e32565a7f599"
    source = "https://download.visualstudio.microsoft.com/download/pr/c7e0c48d-e0ce-4ef9-b30b-41a66a078b0a/26cba85b178af0458f09830a93ab956b/dotnet-runtime-5.0.14-linux-x64.tar.gz"
    source_sha256 = "4e8b468612c6903167c729f32f41d2b0e703fec767e165ed9d5038da6e92d579"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_5.0.14_linux_x64_bionic_b75dd3b7.tar.xz"
    version = "5.0.14"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net:6.0.1:*:*:*:*:*:*:*"
    deprecation_date = "2024-11-08T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-runtime@6.0.1?checksum=f77369477ee8c98402793a2b6ce1f46d663fd0373a93a4cef50eb22d8607773c&download_url=https://download.visualstudio.microsoft.com/download/pr/be8a513c-f3bb-4fbd-b382-6596cf0d67b5/968e205c44eabd205b8ea98be250b880/dotnet-runtime-6.0.1-linux-x64.tar.gz"
    sha256 = "9b55cb4d66a655117bbf2967c9a1c2e1c8157e6edf9ca930e2b3feeae3c1471a"
    source = "https://download.visualstudio.microsoft.com/download/pr/be8a513c-f3bb-4fbd-b382-6596cf0d67b5/968e205c44eabd205b8ea98be250b880/dotnet-runtime-6.0.1-linux-x64.tar.gz"
    source_sha256 = "f77369477ee8c98402793a2b6ce1f46d663fd0373a93a4cef50eb22d8607773c"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_6.0.1_linux_x64_bionic_9b55cb4d.tar.xz"
    version = "6.0.1"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net:6.0.2:*:*:*:*:*:*:*"
    deprecation_date = "2024-11-08T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-runtime@6.0.2?checksum=f70cb7d955aabff1fa9c05dbb4710516bee22e24f0280dbe75f24fb40ab69e1f&download_url=https://download.visualstudio.microsoft.com/download/pr/eec7db31-0187-4751-88ec-53ea526d4d35/d183e3973cc9a4b988cd4d1184db433f/dotnet-runtime-6.0.2-linux-x64.tar.gz"
    sha256 = "5fa2427dd3c2f7eb9cf1516ffb48ec106c487fae496f52537eae60c901869c79"
    source = "https://download.visualstudio.microsoft.com/download/pr/eec7db31-0187-4751-88ec-53ea526d4d35/d183e3973cc9a4b988cd4d1184db433f/dotnet-runtime-6.0.2-linux-x64.tar.gz"
    source_sha256 = "f70cb7d955aabff1fa9c05dbb4710516bee22e24f0280dbe75f24fb40ab69e1f"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_6.0.2_linux_x64_bionic_5fa2427d.tar.xz"
    version = "6.0.2"

  [[metadata.dependency-constraints]]
    constraint = "3.1.*"
    id = "dotnet-runtime"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "5.0.*"
    id = "dotnet-runtime"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "6.0.*"
    id = "dotnet-runtime"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
