api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-runtime"
  id = "paketo-buildpacks/dotnet-core-runtime"
  name = "Paketo .NET Core Runtime Buildpack"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net_core:3.1.18:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-03T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-runtime@3.1.18?checksum=0e529bdb5bb3ce686553cd39aae40007e688e734e1415297d94a4301a2fd3388&download_url=https://download.visualstudio.microsoft.com/download/pr/13a14c60-b4c7-4d48-bef5-8553bb28980d/7b8eb9f74577383064bfb3b02a5964f5/dotnet-runtime-3.1.18-linux-x64.tar.gz"
    sha256 = "44c5b9109a7202eba00e761fbb26fb5717a2ab1eb867c8bff246f7a68614ed90"
    source = "https://download.visualstudio.microsoft.com/download/pr/13a14c60-b4c7-4d48-bef5-8553bb28980d/7b8eb9f74577383064bfb3b02a5964f5/dotnet-runtime-3.1.18-linux-x64.tar.gz"
    source_sha256 = "0e529bdb5bb3ce686553cd39aae40007e688e734e1415297d94a4301a2fd3388"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_3.1.18_linux_x64_bionic_44c5b910.tar.xz"
    version = "3.1.18"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net_core:3.1.19:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-03T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-runtime@3.1.19?checksum=b5e63e998f3c175d4149b8e92b65e156db2192edf7d105b8b1ec19e42c95ec16&download_url=https://download.visualstudio.microsoft.com/download/pr/2600fa33-3746-4ab2-917f-f7dad2eb2e46/8b02443c004709e2ced7634f7ffae7ac/dotnet-runtime-3.1.19-linux-x64.tar.gz"
    sha256 = "28193a415e4a1ce6ac5f0c6820c0bb8b467b954166331b0706d50a533039e2ed"
    source = "https://download.visualstudio.microsoft.com/download/pr/2600fa33-3746-4ab2-917f-f7dad2eb2e46/8b02443c004709e2ced7634f7ffae7ac/dotnet-runtime-3.1.19-linux-x64.tar.gz"
    source_sha256 = "b5e63e998f3c175d4149b8e92b65e156db2192edf7d105b8b1ec19e42c95ec16"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_3.1.19_linux_x64_bionic_28193a41.tar.xz"
    version = "3.1.19"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net:5.0.9:*:*:*:*:*:*:*"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-runtime@5.0.9?checksum=ca143ca29035ebd6acc2b7033d7cdd2b9ceb9e34465ecdb4a7947b92173772ec&download_url=https://download.visualstudio.microsoft.com/download/pr/0c1eabe6-32ef-4785-92d1-8f09a0951b9e/d90c850374a07505bd577d3cff5d7536/dotnet-runtime-5.0.9-linux-x64.tar.gz"
    sha256 = "c3734d7694c701b8761d1ac56dbf24433b6a1d12990090eff3e58a41b3039f36"
    source = "https://download.visualstudio.microsoft.com/download/pr/0c1eabe6-32ef-4785-92d1-8f09a0951b9e/d90c850374a07505bd577d3cff5d7536/dotnet-runtime-5.0.9-linux-x64.tar.gz"
    source_sha256 = "ca143ca29035ebd6acc2b7033d7cdd2b9ceb9e34465ecdb4a7947b92173772ec"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_5.0.9_linux_x64_bionic_c3734d76.tar.xz"
    version = "5.0.9"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net:5.0.10:*:*:*:*:*:*:*"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-runtime@5.0.10?checksum=9067dcfcc4afa699c4074153977c10911116013d44760f84cb2cf84a8edc9d54&download_url=https://download.visualstudio.microsoft.com/download/pr/4bb93b65-658d-4c6c-b4e2-32ec2a3d8aa6/ca3a11e65bcbc6dbb30330a54fcc1059/dotnet-runtime-5.0.10-linux-x64.tar.gz"
    sha256 = "3a4fea7fd812fd6acda0a128d0bf79b8be18b206c0ec52e6acc90da41598b7c6"
    source = "https://download.visualstudio.microsoft.com/download/pr/4bb93b65-658d-4c6c-b4e2-32ec2a3d8aa6/ca3a11e65bcbc6dbb30330a54fcc1059/dotnet-runtime-5.0.10-linux-x64.tar.gz"
    source_sha256 = "9067dcfcc4afa699c4074153977c10911116013d44760f84cb2cf84a8edc9d54"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_5.0.10_linux_x64_bionic_3a4fea7f.tar.xz"
    version = "5.0.10"

  [[metadata.dependency-constraints]]
    constraint = "3.1.*"
    id = "dotnet-runtime"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "5.0.*"
    id = "dotnet-runtime"
    patches = 2

  [[metadata.dependency_deprecation_dates]]
    date = "2022-12-04T00:00:00Z"
    link = "https://dotnet.microsoft.com/platform/support/policy/dotnet-core"
    name = "dotnet-runtime"
    version_line = "3.1.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
