api = "0.8"

[buildpack]
  description = "A buildpack for installing the appropriate .NET Core runtime version"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-runtime"
  id = "paketo-buildpacks/dotnet-core-runtime"
  keywords = ["dotnet", "runtime"]
  name = "Paketo Buildpack for .NET Core Runtime"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/dotnet-core-runtime/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    dotnet-runtime = "6.0.*"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net_core:3.1.29:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-13T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core Runtime"
    purl = "pkg:generic/dotnet-runtime@3.1.29?checksum=c9d1a4e88cc5801c93aaa2448521d5eed5045ee46a0ce1f4a33b6efaed796c11&download_url=https://download.visualstudio.microsoft.com/download/pr/8a8cff44-0a23-413a-8643-2a0fa3b4da3c/c937fe6ed4d60efb1ef2929d983398cd/dotnet-runtime-3.1.29-linux-x64.tar.gz"
    sha256 = "319dbf1a8699724f7e1a6856a77f2cf41d784953913a78aa6349690f9cab3fc4"
    source = "https://download.visualstudio.microsoft.com/download/pr/8a8cff44-0a23-413a-8643-2a0fa3b4da3c/c937fe6ed4d60efb1ef2929d983398cd/dotnet-runtime-3.1.29-linux-x64.tar.gz"
    source_sha256 = "c9d1a4e88cc5801c93aaa2448521d5eed5045ee46a0ce1f4a33b6efaed796c11"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_3.1.29_linux_x64_bionic_319dbf1a.tar.xz"
    version = "3.1.29"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net_core:3.1.30:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-13T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core Runtime"
    purl = "pkg:generic/dotnet-runtime@3.1.30?checksum=b2600a6135ab07ed14f0fd23677511cbb4b6bad7c62f42b2215834b8a2cbc867&download_url=https://download.visualstudio.microsoft.com/download/pr/9f6128a8-3962-4018-b9b0-9608b9aecec8/f46a672e0117d9128acdbc82cc314e20/dotnet-runtime-3.1.30-linux-x64.tar.gz"
    sha256 = "548b8ad294f4a14f4a1f7919a182aa34caa56e593cd54a0cb147aa3bdec4cac6"
    source = "https://download.visualstudio.microsoft.com/download/pr/9f6128a8-3962-4018-b9b0-9608b9aecec8/f46a672e0117d9128acdbc82cc314e20/dotnet-runtime-3.1.30-linux-x64.tar.gz"
    source_sha256 = "b2600a6135ab07ed14f0fd23677511cbb4b6bad7c62f42b2215834b8a2cbc867"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_3.1.30_linux_x64_bionic_548b8ad2.tar.xz"
    version = "3.1.30"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net:6.0.9:*:*:*:*:*:*:*"
    deprecation_date = "2024-11-12T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core Runtime"
    purl = "pkg:generic/dotnet-runtime@6.0.9?checksum=3ffe807c2f0efc81410d31d96f7c1278cd1a2357d71da790e59b04e48d3231c5&download_url=https://download.visualstudio.microsoft.com/download/pr/05f1a3dd-75f2-49f4-a976-25ce08f77cbb/b6e8e327a84b91513c2744bfccf90140/dotnet-runtime-6.0.9-linux-x64.tar.gz"
    sha256 = "a691f754903789bd990106ae8e8da4c12116b2c103cef0f020f60c19dd6cb35b"
    source = "https://download.visualstudio.microsoft.com/download/pr/05f1a3dd-75f2-49f4-a976-25ce08f77cbb/b6e8e327a84b91513c2744bfccf90140/dotnet-runtime-6.0.9-linux-x64.tar.gz"
    source_sha256 = "3ffe807c2f0efc81410d31d96f7c1278cd1a2357d71da790e59b04e48d3231c5"
    stacks = ["io.buildpacks.stacks.bionic", "io.buildpacks.stacks.jammy"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_6.0.9_linux_x64_bionic_a691f754.tar.xz"
    version = "6.0.9"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net:6.0.10:*:*:*:*:*:*:*"
    deprecation_date = "2024-11-12T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core Runtime"
    purl = "pkg:generic/dotnet-runtime@6.0.10?checksum=c7e7e1faa375ca7b98124ed5c694f9a28878bb243b4301ce0966100ae38910e6&download_url=https://download.visualstudio.microsoft.com/download/pr/48fbc600-8228-424e-aaed-52b7e601c277/c493b8ac4629341f1e5acc4ff515fead/dotnet-runtime-6.0.10-linux-x64.tar.gz"
    sha256 = "20d2bf6f1f67a9869deabbb6964d841e42cb2a6056534f43c16e188c2f933911"
    source = "https://download.visualstudio.microsoft.com/download/pr/48fbc600-8228-424e-aaed-52b7e601c277/c493b8ac4629341f1e5acc4ff515fead/dotnet-runtime-6.0.10-linux-x64.tar.gz"
    source_sha256 = "c7e7e1faa375ca7b98124ed5c694f9a28878bb243b4301ce0966100ae38910e6"
    stacks = ["io.buildpacks.stacks.bionic", "io.buildpacks.stacks.jammy"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_6.0.10_linux_x64_bionic_20d2bf6f.tar.xz"
    version = "6.0.10"

  [[metadata.dependency-constraints]]
    constraint = "3.1.*"
    id = "dotnet-runtime"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "6.0.*"
    id = "dotnet-runtime"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "7.0.*"
    id = "dotnet-runtime"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.buildpacks.stacks.jammy"
