api = "0.6"

[buildpack]
  description = "A buildpack for installing the approriate .NET Core runtime version"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-runtime"
  id = "paketo-buildpacks/dotnet-core-runtime"
  keywords = ["dotnet", "runtime"]
  name = "Paketo .NET Core Runtime Buildpack"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/dotnet-core-runtime/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    dotnet-runtime = "5.0.*"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net_core:3.1.22:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-03T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-runtime@3.1.22?checksum=8a5b1a9a8ca0b927450c14671e879f5e1d99906e4b67e2933047c888fda879e1&download_url=https://download.visualstudio.microsoft.com/download/pr/8a11a2ba-d599-486f-ba61-9e420bc4a2bb/db9d61f28e0a688adc83687b611702ff/dotnet-runtime-3.1.22-linux-x64.tar.gz"
    sha256 = "a0e5fc49247e55b3c290647e16a12c5ca312c34c4796822ac37be21b583dff59"
    source = "https://download.visualstudio.microsoft.com/download/pr/8a11a2ba-d599-486f-ba61-9e420bc4a2bb/db9d61f28e0a688adc83687b611702ff/dotnet-runtime-3.1.22-linux-x64.tar.gz"
    source_sha256 = "8a5b1a9a8ca0b927450c14671e879f5e1d99906e4b67e2933047c888fda879e1"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_3.1.22_linux_x64_bionic_a0e5fc49.tar.xz"
    version = "3.1.22"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net_core:3.1.23:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-03T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-runtime@3.1.23?checksum=171738bc83f794870f8c2e03e9c63a0f3f152b5ff646a225a7c90a2f29458db3&download_url=https://download.visualstudio.microsoft.com/download/pr/4022ad95-d68e-46de-a849-f66d482d6b45/f67e642ff95d838d03a0548cc4ea0ba1/dotnet-runtime-3.1.23-linux-x64.tar.gz"
    sha256 = "c0b74c576ef5637a335a759fc35b69d63030a1fde8e13cea320cc524aca2a05a"
    source = "https://download.visualstudio.microsoft.com/download/pr/4022ad95-d68e-46de-a849-f66d482d6b45/f67e642ff95d838d03a0548cc4ea0ba1/dotnet-runtime-3.1.23-linux-x64.tar.gz"
    source_sha256 = "171738bc83f794870f8c2e03e9c63a0f3f152b5ff646a225a7c90a2f29458db3"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_3.1.23_linux_x64_bionic_c0b74c57.tar.xz"
    version = "3.1.23"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net:5.0.14:*:*:*:*:*:*:*"
    deprecation_date = "2022-05-08T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-runtime@5.0.14?checksum=4e8b468612c6903167c729f32f41d2b0e703fec767e165ed9d5038da6e92d579&download_url=https://download.visualstudio.microsoft.com/download/pr/c7e0c48d-e0ce-4ef9-b30b-41a66a078b0a/26cba85b178af0458f09830a93ab956b/dotnet-runtime-5.0.14-linux-x64.tar.gz"
    sha256 = "b75dd3b7b8f8059388749c85cf9b2668cd01ce1f8e91c902a883e32565a7f599"
    source = "https://download.visualstudio.microsoft.com/download/pr/c7e0c48d-e0ce-4ef9-b30b-41a66a078b0a/26cba85b178af0458f09830a93ab956b/dotnet-runtime-5.0.14-linux-x64.tar.gz"
    source_sha256 = "4e8b468612c6903167c729f32f41d2b0e703fec767e165ed9d5038da6e92d579"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_5.0.14_linux_x64_bionic_b75dd3b7.tar.xz"
    version = "5.0.14"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net:5.0.15:*:*:*:*:*:*:*"
    deprecation_date = "2022-05-08T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-runtime@5.0.15?checksum=32546d3282b8d8c9c9e9961c091cb6b1ad5be8ca10f0c141901bb80c93470ebb&download_url=https://download.visualstudio.microsoft.com/download/pr/546d50b2-d85c-433f-b13b-b896f1bc1916/17d7bbb674bf67c3d490489b20a437b7/dotnet-runtime-5.0.15-linux-x64.tar.gz"
    sha256 = "7428cc24fa014cfcd7cb0f24f5f4f5dfc7d82eb952dad4abb4107142274a7244"
    source = "https://download.visualstudio.microsoft.com/download/pr/546d50b2-d85c-433f-b13b-b896f1bc1916/17d7bbb674bf67c3d490489b20a437b7/dotnet-runtime-5.0.15-linux-x64.tar.gz"
    source_sha256 = "32546d3282b8d8c9c9e9961c091cb6b1ad5be8ca10f0c141901bb80c93470ebb"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_5.0.15_linux_x64_bionic_7428cc24.tar.xz"
    version = "5.0.15"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net:6.0.2:*:*:*:*:*:*:*"
    deprecation_date = "2024-11-08T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-runtime@6.0.2?checksum=f70cb7d955aabff1fa9c05dbb4710516bee22e24f0280dbe75f24fb40ab69e1f&download_url=https://download.visualstudio.microsoft.com/download/pr/eec7db31-0187-4751-88ec-53ea526d4d35/d183e3973cc9a4b988cd4d1184db433f/dotnet-runtime-6.0.2-linux-x64.tar.gz"
    sha256 = "5fa2427dd3c2f7eb9cf1516ffb48ec106c487fae496f52537eae60c901869c79"
    source = "https://download.visualstudio.microsoft.com/download/pr/eec7db31-0187-4751-88ec-53ea526d4d35/d183e3973cc9a4b988cd4d1184db433f/dotnet-runtime-6.0.2-linux-x64.tar.gz"
    source_sha256 = "f70cb7d955aabff1fa9c05dbb4710516bee22e24f0280dbe75f24fb40ab69e1f"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_6.0.2_linux_x64_bionic_5fa2427d.tar.xz"
    version = "6.0.2"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net:6.0.3:*:*:*:*:*:*:*"
    deprecation_date = "2024-11-08T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-runtime@6.0.3?checksum=275d9eb77d82665ac57089d88d9010a7f86329bdcf6997908543c701eaf196ec&download_url=https://download.visualstudio.microsoft.com/download/pr/4e766615-57e6-4b1d-a574-25eeb7a71107/9f95f74c33711e085302ffd644ef86ee/dotnet-runtime-6.0.3-linux-x64.tar.gz"
    sha256 = "2a4a5eb2ec3c38ce526a6ca8229fd9637ba4bb5eee0abdbda30d7f2872c97d17"
    source = "https://download.visualstudio.microsoft.com/download/pr/4e766615-57e6-4b1d-a574-25eeb7a71107/9f95f74c33711e085302ffd644ef86ee/dotnet-runtime-6.0.3-linux-x64.tar.gz"
    source_sha256 = "275d9eb77d82665ac57089d88d9010a7f86329bdcf6997908543c701eaf196ec"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_6.0.3_linux_x64_bionic_2a4a5eb2.tar.xz"
    version = "6.0.3"

  [[metadata.dependency-constraints]]
    constraint = "3.1.*"
    id = "dotnet-runtime"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "5.0.*"
    id = "dotnet-runtime"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "6.0.*"
    id = "dotnet-runtime"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
