api = "0.8"

[buildpack]
  description = "A buildpack for installing the appropriate .NET Core runtime version"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-runtime"
  id = "paketo-buildpacks/dotnet-core-runtime"
  keywords = ["dotnet", "runtime"]
  name = "Paketo Buildpack for .NET Core Runtime"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/dotnet-core-runtime/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    dotnet-runtime = "6.0.*"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net:6.0.11:*:*:*:*:*:*:*"
    deprecation_date = "2024-11-12T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core Runtime"
    purl = "pkg:generic/dotnet-runtime@6.0.11?checksum=8b5b933de46d7d885ce99f4e5b49204ab46dd1c0eac9c976ef39558e20a490bf&download_url=https://download.visualstudio.microsoft.com/download/pr/367108bb-8782-4f0b-839d-c98191b7729a/94185f91ef33890816a5846a374b74b7/dotnet-runtime-6.0.11-linux-x64.tar.gz"
    sha256 = "6fe779b0611a6e69423d3c8ffad21586ee492ba4983b43d9b3739087d70ca652"
    source = "https://download.visualstudio.microsoft.com/download/pr/367108bb-8782-4f0b-839d-c98191b7729a/94185f91ef33890816a5846a374b74b7/dotnet-runtime-6.0.11-linux-x64.tar.gz"
    source_sha256 = "8b5b933de46d7d885ce99f4e5b49204ab46dd1c0eac9c976ef39558e20a490bf"
    stacks = ["io.buildpacks.stacks.bionic", "io.buildpacks.stacks.jammy"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_6.0.11_linux_x64_bionic_6fe779b0.tar.xz"
    version = "6.0.11"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net:6.0.12:*:*:*:*:*:*:*"
    deprecation_date = "2024-11-12T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core Runtime"
    purl = "pkg:generic/dotnet-runtime@6.0.12?checksum=2ad75c53eea6ad561c22efc53f7a78db0ed82d8ca3a1e1d39d0c97b41348bdba&download_url=https://download.visualstudio.microsoft.com/download/pr/7d543956-0b80-4c08-910e-c8c388f5fab8/01d45a3686e72f70be51b3f98569c6b1/dotnet-runtime-6.0.12-linux-x64.tar.gz"
    sha256 = "d551079b8fb874e5858a108ad2a3694cfa7e74e44e6dcb8c78679b7d7bede2ac"
    source = "https://download.visualstudio.microsoft.com/download/pr/7d543956-0b80-4c08-910e-c8c388f5fab8/01d45a3686e72f70be51b3f98569c6b1/dotnet-runtime-6.0.12-linux-x64.tar.gz"
    source_sha256 = "2ad75c53eea6ad561c22efc53f7a78db0ed82d8ca3a1e1d39d0c97b41348bdba"
    stacks = ["io.buildpacks.stacks.bionic", "io.buildpacks.stacks.jammy"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_6.0.12_linux_x64_bionic_d551079b.tar.xz"
    version = "6.0.12"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net:7.0.0:*:*:*:*:*:*:*"
    deprecation_date = "2024-05-14T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core Runtime"
    purl = "pkg:generic/dotnet-runtime@7.0.0?checksum=47538f598b5c60a51a1bfa643eae040b8e3832de1c2c2dcb1d3f2da6c7c4d76f&download_url=https://download.visualstudio.microsoft.com/download/pr/d4b0a69b-29cd-40ef-9e95-a8d16f0ff346/5844add76ae3917af9efd59d95e3cbd4/dotnet-runtime-7.0.0-linux-x64.tar.gz"
    sha256 = "121e2ee67bf50dd3f007b24e9753731a897df3656de2d667628a6112e654a938"
    source = "https://download.visualstudio.microsoft.com/download/pr/d4b0a69b-29cd-40ef-9e95-a8d16f0ff346/5844add76ae3917af9efd59d95e3cbd4/dotnet-runtime-7.0.0-linux-x64.tar.gz"
    source_sha256 = "47538f598b5c60a51a1bfa643eae040b8e3832de1c2c2dcb1d3f2da6c7c4d76f"
    stacks = ["io.buildpacks.stacks.bionic", "io.buildpacks.stacks.jammy"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_7.0.0_linux_x64_bionic_121e2ee6.tar.xz"
    version = "7.0.0"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net:7.0.1:*:*:*:*:*:*:*"
    deprecation_date = "2024-05-14T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core Runtime"
    purl = "pkg:generic/dotnet-runtime@7.0.1?checksum=b82436603a60ec2e801d3f0c734f1b62313c7b6bd132151aa4e6b0585047cb7a&download_url=https://download.visualstudio.microsoft.com/download/pr/0b330412-234f-48c5-957c-c3c8c854a400/8d9a07cc153fd16a828d78c136b47e6f/dotnet-runtime-7.0.1-linux-x64.tar.gz"
    sha256 = "fc80048a31fd238efecd5a46973ae9882973abc1ebca192fdca76cbcf438f93b"
    source = "https://download.visualstudio.microsoft.com/download/pr/0b330412-234f-48c5-957c-c3c8c854a400/8d9a07cc153fd16a828d78c136b47e6f/dotnet-runtime-7.0.1-linux-x64.tar.gz"
    source_sha256 = "b82436603a60ec2e801d3f0c734f1b62313c7b6bd132151aa4e6b0585047cb7a"
    stacks = ["io.buildpacks.stacks.bionic", "io.buildpacks.stacks.jammy"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_7.0.1_linux_x64_bionic_fc80048a.tar.xz"
    version = "7.0.1"

  [[metadata.dependency-constraints]]
    constraint = "6.0.*"
    id = "dotnet-runtime"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "7.0.*"
    id = "dotnet-runtime"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.buildpacks.stacks.jammy"
