api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-runtime"
  id = "paketo-buildpacks/dotnet-core-runtime"
  name = "Paketo .NET Core Runtime Buildpack"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    deprecation_date = "2022-12-04T00:00:00Z"
    id = "dotnet-runtime"
    sha256 = "02a6437a9f97d12917c03a13f8040e644343b1704fd68b74af5be60e24c02405"
    source = "https://download.visualstudio.microsoft.com/download/pr/7a4bfa73-e500-45aa-8e10-04dc4910d8ae/f8b74c973752d3ea095fe06aa625f7f7/dotnet-runtime-3.1.17-linux-x64.tar.gz"
    source_sha256 = "678154c84e1034a4b094a210a8e9dec08fb0dbc5cde3304a85d549d9e6762a75"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_3.1.17_linux_x64_any-stack_02a6437a.tar.xz"
    version = "3.1.17"

  [[metadata.dependencies]]
    deprecation_date = "2022-12-04T00:00:00Z"
    id = "dotnet-runtime"
    sha256 = "fb39d01d2cebf4066903076b08921f6ddfbfb6f14bf6ff4c63564c5bca427549"
    source = "https://download.visualstudio.microsoft.com/download/pr/13a14c60-b4c7-4d48-bef5-8553bb28980d/7b8eb9f74577383064bfb3b02a5964f5/dotnet-runtime-3.1.18-linux-x64.tar.gz"
    source_sha256 = "0e529bdb5bb3ce686553cd39aae40007e688e734e1415297d94a4301a2fd3388"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_3.1.18_linux_x64_any-stack_fb39d01d.tar.xz"
    version = "3.1.18"

  [[metadata.dependencies]]
    id = "dotnet-runtime"
    sha256 = "d746012f2ec580a151bef0fe1ea4bcebf5098b17487535089a00c3a331ec3217"
    source = "https://download.visualstudio.microsoft.com/download/pr/50687c84-e120-4410-bd4a-b1e0869d03f4/6038576259f95ef61d4d103ee3967130/dotnet-runtime-5.0.8-linux-x64.tar.gz"
    source_sha256 = "2a729240c6518c7c995769b1be7757e2e0388a58dca65236561a300f60ef096a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_5.0.8_linux_x64_any-stack_d746012f.tar.xz"
    version = "5.0.8"

  [[metadata.dependencies]]
    id = "dotnet-runtime"
    sha256 = "b605c2f7fbc88f97f98f2c5704dff6cebb934152754bed36b98c24a6c875fdc1"
    source = "https://download.visualstudio.microsoft.com/download/pr/0c1eabe6-32ef-4785-92d1-8f09a0951b9e/d90c850374a07505bd577d3cff5d7536/dotnet-runtime-5.0.9-linux-x64.tar.gz"
    source_sha256 = "ca143ca29035ebd6acc2b7033d7cdd2b9ceb9e34465ecdb4a7947b92173772ec"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_5.0.9_linux_x64_any-stack_b605c2f7.tar.xz"
    version = "5.0.9"

  [[metadata.dependency_deprecation_dates]]
    date = "2022-12-04T00:00:00Z"
    link = "https://dotnet.microsoft.com/platform/support/policy/dotnet-core"
    name = "dotnet-runtime"
    version_line = "3.1.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
