api = "0.8"

[buildpack]
  description = "A buildpack for installing the appropriate .NET Core runtime version"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-runtime"
  id = "paketo-buildpacks/dotnet-core-runtime"
  keywords = ["dotnet", "runtime"]
  name = "Paketo .NET Core Runtime Buildpack"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/dotnet-core-runtime/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    dotnet-runtime = "6.0.*"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net_core:3.1.26:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-13T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core Runtime"
    purl = "pkg:generic/dotnet-runtime@3.1.26?checksum=ef6a030adfc4708e2840c85a69038c29a1e98a0bc009a1828034c15e6c30c0e6&download_url=https://download.visualstudio.microsoft.com/download/pr/a14c8e4d-a22b-47f8-953c-bb4337634513/58017d103d432f7106c44b0891936aba/dotnet-runtime-3.1.26-linux-x64.tar.gz"
    sha256 = "e85291aa28e4943f93400cb030ec6150dddd84b1424169a60f48ed0de8166d5c"
    source = "https://download.visualstudio.microsoft.com/download/pr/a14c8e4d-a22b-47f8-953c-bb4337634513/58017d103d432f7106c44b0891936aba/dotnet-runtime-3.1.26-linux-x64.tar.gz"
    source_sha256 = "ef6a030adfc4708e2840c85a69038c29a1e98a0bc009a1828034c15e6c30c0e6"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_3.1.26_linux_x64_bionic_e85291aa.tar.xz"
    version = "3.1.26"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net_core:3.1.27:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-13T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core Runtime"
    purl = "pkg:generic/dotnet-runtime@3.1.27?checksum=a125268b4bff43e501c72ccf946bf978b43afcc8d37f1150f17cb4f70a1dd6b5&download_url=https://download.visualstudio.microsoft.com/download/pr/26fcc6c4-0154-4b67-bfe0-85af31f06e7a/b17c38beb93d1642cc8f04d1f18908a4/dotnet-runtime-3.1.27-linux-x64.tar.gz"
    sha256 = "c0d6d29e052f09037be4667b4c20d42c2ee8ee61b2fc744f63f5557908cf36e8"
    source = "https://download.visualstudio.microsoft.com/download/pr/26fcc6c4-0154-4b67-bfe0-85af31f06e7a/b17c38beb93d1642cc8f04d1f18908a4/dotnet-runtime-3.1.27-linux-x64.tar.gz"
    source_sha256 = "a125268b4bff43e501c72ccf946bf978b43afcc8d37f1150f17cb4f70a1dd6b5"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_3.1.27_linux_x64_bionic_c0d6d29e.tar.xz"
    version = "3.1.27"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net:6.0.6:*:*:*:*:*:*:*"
    deprecation_date = "2024-11-12T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core Runtime"
    purl = "pkg:generic/dotnet-runtime@6.0.6?checksum=9a3e9b9f39ca51c354725738fea4b931dd4a85e30d0373f0dd2c0517f7de65ac&download_url=https://download.visualstudio.microsoft.com/download/pr/ec4172e3-077a-42c0-859d-349e517d7935/82d945cdc4c33fbe440a86a240a58a41/dotnet-runtime-6.0.6-linux-x64.tar.gz"
    sha256 = "aa9cd7529c2797d92daadefac86e57fe2a25a1d248464323278b3b39ac6f2682"
    source = "https://download.visualstudio.microsoft.com/download/pr/ec4172e3-077a-42c0-859d-349e517d7935/82d945cdc4c33fbe440a86a240a58a41/dotnet-runtime-6.0.6-linux-x64.tar.gz"
    source_sha256 = "9a3e9b9f39ca51c354725738fea4b931dd4a85e30d0373f0dd2c0517f7de65ac"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_6.0.6_linux_x64_bionic_aa9cd752.tar.xz"
    version = "6.0.6"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net:6.0.7:*:*:*:*:*:*:*"
    deprecation_date = "2024-11-12T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core Runtime"
    purl = "pkg:generic/dotnet-runtime@6.0.7?checksum=6ed407c5c6d365673e707bd9532a0db78d43fbdb2cea99674a841c784cba5063&download_url=https://download.visualstudio.microsoft.com/download/pr/bd828687-1706-4041-a804-5e93631fe256/d4ec75936459a7e8c772c929edcbfeda/dotnet-runtime-6.0.7-linux-x64.tar.gz"
    sha256 = "d5412b0c5a329500b027335837fc77a9b035d525c015a25ed82a5bd548e3e84b"
    source = "https://download.visualstudio.microsoft.com/download/pr/bd828687-1706-4041-a804-5e93631fe256/d4ec75936459a7e8c772c929edcbfeda/dotnet-runtime-6.0.7-linux-x64.tar.gz"
    source_sha256 = "6ed407c5c6d365673e707bd9532a0db78d43fbdb2cea99674a841c784cba5063"
    stacks = ["io.buildpacks.stacks.bionic", "io.buildpacks.stacks.jammy"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_6.0.7_linux_x64_bionic_d5412b0c.tar.xz"
    version = "6.0.7"

  [[metadata.dependency-constraints]]
    constraint = "3.1.*"
    id = "dotnet-runtime"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "6.0.*"
    id = "dotnet-runtime"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
