api = "0.5"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-runtime"
  id = "paketo-buildpacks/dotnet-core-runtime"
  name = "Paketo .NET Core Runtime Buildpack"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net_core:3.1.19:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-03T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-runtime@3.1.19?checksum=b5e63e998f3c175d4149b8e92b65e156db2192edf7d105b8b1ec19e42c95ec16&download_url=https://download.visualstudio.microsoft.com/download/pr/2600fa33-3746-4ab2-917f-f7dad2eb2e46/8b02443c004709e2ced7634f7ffae7ac/dotnet-runtime-3.1.19-linux-x64.tar.gz"
    sha256 = "28193a415e4a1ce6ac5f0c6820c0bb8b467b954166331b0706d50a533039e2ed"
    source = "https://download.visualstudio.microsoft.com/download/pr/2600fa33-3746-4ab2-917f-f7dad2eb2e46/8b02443c004709e2ced7634f7ffae7ac/dotnet-runtime-3.1.19-linux-x64.tar.gz"
    source_sha256 = "b5e63e998f3c175d4149b8e92b65e156db2192edf7d105b8b1ec19e42c95ec16"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_3.1.19_linux_x64_bionic_28193a41.tar.xz"
    version = "3.1.19"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net_core:3.1.20:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-03T00:00:00Z"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-runtime@3.1.20?checksum=b94c977f970db78b2c0fcf35ed4bcf4b430e73dd9cee54d23a7e0015d4f4ada7&download_url=https://download.visualstudio.microsoft.com/download/pr/e22ce067-99cb-4e59-8623-97fab16a0f5e/9d4825680d3f3a1850bbd3acb9ee9d28/dotnet-runtime-3.1.20-linux-x64.tar.gz"
    sha256 = "280459701eee9f7d9cfea740d45978556fa46753bfc7b858b7c83014ae209083"
    source = "https://download.visualstudio.microsoft.com/download/pr/e22ce067-99cb-4e59-8623-97fab16a0f5e/9d4825680d3f3a1850bbd3acb9ee9d28/dotnet-runtime-3.1.20-linux-x64.tar.gz"
    source_sha256 = "b94c977f970db78b2c0fcf35ed4bcf4b430e73dd9cee54d23a7e0015d4f4ada7"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_3.1.20_linux_x64_bionic_28045970.tar.xz"
    version = "3.1.20"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net:5.0.10:*:*:*:*:*:*:*"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-runtime@5.0.10?checksum=9067dcfcc4afa699c4074153977c10911116013d44760f84cb2cf84a8edc9d54&download_url=https://download.visualstudio.microsoft.com/download/pr/4bb93b65-658d-4c6c-b4e2-32ec2a3d8aa6/ca3a11e65bcbc6dbb30330a54fcc1059/dotnet-runtime-5.0.10-linux-x64.tar.gz"
    sha256 = "3a4fea7fd812fd6acda0a128d0bf79b8be18b206c0ec52e6acc90da41598b7c6"
    source = "https://download.visualstudio.microsoft.com/download/pr/4bb93b65-658d-4c6c-b4e2-32ec2a3d8aa6/ca3a11e65bcbc6dbb30330a54fcc1059/dotnet-runtime-5.0.10-linux-x64.tar.gz"
    source_sha256 = "9067dcfcc4afa699c4074153977c10911116013d44760f84cb2cf84a8edc9d54"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_5.0.10_linux_x64_bionic_3a4fea7f.tar.xz"
    version = "5.0.10"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:.net:5.0.11:*:*:*:*:*:*:*"
    id = "dotnet-runtime"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-runtime@5.0.11?checksum=7da7bc862ccbc58cbf09d713cb77d6473a80233cb132ffc3accd124a0d6b1b80&download_url=https://download.visualstudio.microsoft.com/download/pr/4652f15f-0061-4b13-aa61-0c1d23c3b290/af67e2036f0086a3794ba988233b41ae/dotnet-runtime-5.0.11-linux-x64.tar.gz"
    sha256 = "bab4d6891377e665c485ab12f0e4482b3cc4dd3ccedbe63a6d48bd5cd7c3c13a"
    source = "https://download.visualstudio.microsoft.com/download/pr/4652f15f-0061-4b13-aa61-0c1d23c3b290/af67e2036f0086a3794ba988233b41ae/dotnet-runtime-5.0.11-linux-x64.tar.gz"
    source_sha256 = "7da7bc862ccbc58cbf09d713cb77d6473a80233cb132ffc3accd124a0d6b1b80"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-runtime/dotnet-runtime_5.0.11_linux_x64_bionic_bab4d689.tar.xz"
    version = "5.0.11"

  [[metadata.dependency-constraints]]
    constraint = "3.1.*"
    id = "dotnet-runtime"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "5.0.*"
    id = "dotnet-runtime"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
